<?php

namespace AppBundle\Repository;

/**
 * abcdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abcdRepository extends \Doctrine\ORM\EntityRepository
{
}
